name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and test project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [14]
        working-directory: [./portfolio]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false 

      - name: Install and Build ğŸ”§
        working-directory: ${{ matrix.working-directory }}
        run: |
          yarn install
          yarn generate

      - name: Deploy ğŸš€
        working-directory: ${{ matrix.working-directory }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: dist
