name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and test project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [14]
        working-directory: [./portfolio]

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Install packages
        working-directory: ${{ matrix.working-directory }}
        run: yarn install

      - name: Lint project
        working-directory: ${{ matrix.working-directory }}
        run: yarn lint

      - name: Test project
        working-directory: ${{ matrix.working-directory }}
        run: yarn test

      - name: Generate project
        working-directory: ${{ matrix.working-directory }}
        run: yarn generate

      - name: Deploy üöÄ
        working-directory: ${{ matrix.working-directory }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: dist
